### ISSUE TITLE
adding readme would help in this repo

### ISSUE THREAD

**Issue by NirmalSilwal** [gagangaur/Rest-API-Spring-Boot#1]
Hi @gagangaur , the project seems nice. How about adding some project descriptions, maybe code flow / how to run the project would be useful.

What do you say on this?

**Comment by gagangaur** [comment]
Great idea @NirmalSilwal  thanks for your interest and suggestion in the project, currently I am working on frontend of the project using react and integration of spring security once it's done will surely update this and if you love to contribute on this its highly appreciated ☺

**Comment by NirmalSilwal** [comment]
sure @gagangaur 

I am currently exploring web development space. Would love to contribute.
